# Generated by Django 5.0.7 on 2024-07-26 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RefTag",
            fields=[
                ("ref_id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_no", models.CharField(blank=True, max_length=255, null=True)),
                ("part_code", models.CharField(blank=True, max_length=255, null=True)),
                ("part_name", models.CharField(blank=True, max_length=255, null=True)),
                ("model_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "stock_inout",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "whouse_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("qr_code", models.CharField(max_length=255)),
                (
                    "ref_tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="print_tag_ac_app.reftag",
                    ),
                ),
            ],
        ),
    ]
